# Generated by Django 3.0.7 on 2020-06-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefield',
            name='is_main_bool',
            field=models.BooleanField(verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='fieldscope',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Раздел'),
        ),
    ]
