# Generated by Django 3.0.7 on 2020-06-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200624_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldscope',
            options={},
        ),
    ]
