# Generated by Django 3.0.7 on 2020-06-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200624_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldscope',
            options={'verbose_name': 'Тематика', 'verbose_name_plural': 'Тематики'},
        ),
        migrations.AlterField(
            model_name='articlefield',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlefield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.FieldScope', verbose_name='Раздел'),
        ),
    ]
