# Generated by Django 3.0.7 on 2020-06-24 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200624_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='articles.FieldScope', verbose_name='Раздел'),
        ),
    ]
