# Generated by Django 3.0.7 on 2020-06-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_fieldscope_flields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldscope',
            old_name='flields',
            new_name='field_name',
        ),
    ]
