# Generated by Django 3.0.7 on 2020-06-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200624_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldscope',
            name='field_name',
        ),
        migrations.AddField(
            model_name='article',
            name='field_name',
            field=models.ManyToManyField(through='articles.ArticleField', to='articles.FieldScope'),
        ),
    ]
