# Generated by Django 3.0.7 on 2020-06-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200624_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='field_name',
            field=models.ManyToManyField(related_name='field_name', through='articles.ArticleField', to='articles.FieldScope'),
        ),
    ]
