# Generated by Django 3.0.7 on 2020-06-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200624_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='field_name',
            field=models.ManyToManyField(related_name='fields_names', through='articles.ArticleField', to='articles.FieldScope'),
        ),
    ]
